"""Additional Pune / PCMC vendor leads beyond household — imported by generate_vendor_leads.py."""

EXTRA_VENDORS = [
    # ── Delivery ──
    {
        "business_name": "CourierBook Pune",
        "contact_person": "",
        "shop_office": "CourierBook (platform hub)",
        "building": "",
        "street": "Doorstep pickup — Hinjewadi, Wakad, PCMC",
        "area": "Pune / PCMC",
        "city": "Pune",
        "pin": "411057",
        "state": "Maharashtra",
        "phone1": "+91 8209384119",
        "phone2": "",
        "email1": "",
        "email2": "",
        "website": "https://www.courierbook.in/courier-service-in-pune/",
        "maps_name": "CourierBook courier service Pune",
        "services_offered": "Same-day Pune city, inter-city courier, doorstep pickup 60+ areas",
        "rating": "Website",
        "hours": "Same-day slots",
        "service_areas": "Hinjewadi, Wakad, PCMC, Baner, Kothrud, Hadapsar",
        "source": "courierbook.in",
        "notes": "Platform aggregator — onboard as partner network",
        "service_ids": ["dl-sameday", "dl-parcel", "dl-doc", "dl-intercity"],
    },
    {
        "business_name": "Professional Courier Service Wakad",
        "contact_person": "",
        "shop_office": "Shop No. 6, Dhanraj Building, B wing",
        "building": "Dhanraj Building",
        "street": "Kaspate Wasti",
        "area": "Wakad",
        "city": "Pune",
        "pin": "411057",
        "state": "Maharashtra",
        "phone1": "+91 9922912559",
        "phone2": "",
        "email1": "",
        "email2": "",
        "website": "https://wakad.in/item/professional-courier-service-wakad/",
        "maps_name": "Professional Courier Service Wakad",
        "services_offered": "Local & national courier, document delivery",
        "rating": "Wakad.in listing",
        "hours": "Mon-Sun 9:00 AM - 6:00 PM",
        "service_areas": "Wakad, Kaspate Wasti, PCMC",
        "source": "Wakad.in",
        "notes": "",
        "service_ids": ["dl-sameday", "dl-doc", "dl-parcel"],
    },
    {
        "business_name": "Shree Maruti Courier Service Wakad",
        "contact_person": "",
        "shop_office": "Shop No 2/125/1/1/18",
        "building": "",
        "street": "Swami Vivekananda, Opposite Lad Restaurant",
        "area": "Wakad",
        "city": "Pune",
        "pin": "411057",
        "state": "Maharashtra",
        "phone1": "+91 8856974665",
        "phone2": "",
        "email1": "",
        "email2": "",
        "website": "https://nearme.shreemaruti.com/locator/pune/wakad/",
        "maps_name": "Shree Maruti Courier Service Wakad",
        "services_offered": "Express, hyperlocal, national courier",
        "rating": "Maruti locator",
        "hours": "",
        "service_areas": "Wakad, Pune, PCMC",
        "source": "Shree Maruti locator",
        "notes": "",
        "service_ids": ["dl-sameday", "dl-intercity", "dl-bulk"],
    },
    {
        "business_name": "DTDC Wakad",
        "contact_person": "",
        "shop_office": "DTDC Wakad",
        "building": "",
        "street": "29, Jagtap Dairy, Near Hotel Waghjai",
        "area": "Wakad",
        "city": "Pimpri Chinchwad",
        "pin": "411027",
        "state": "Maharashtra",
        "phone1": "+91 2027279828",
        "phone2": "",
        "email1": "",
        "email2": "",
        "website": "https://www.dtdc.in/",
        "maps_name": "DTDC Wakad PCMC",
        "services_offered": "Local, national, international courier; doorstep pickup",
        "rating": "AskLaila listing",
        "hours": "",
        "service_areas": "Wakad, PCMC, Pune",
        "source": "AskLaila + DTDC",
        "notes": "",
        "service_ids": ["dl-sameday", "dl-intercity", "dl-bulk", "dl-doc"],
    },
    # ── Two-wheeler ──
    {
        "business_name": "BikeFix Pune",
        "contact_person": "",
        "shop_office": "BikeFix (doorstep service)",
        "building": "",
        "street": "",
        "area": "Pune & PCMC",
        "city": "Pune",
        "pin": "",
        "state": "Maharashtra",
        "phone1": "+91 7507296501",
        "phone2": "",
        "email1": "",
        "email2": "",
        "website": "https://www.bikefixpune.in/",
        "maps_name": "BikeFix Pune doorstep bike service",
        "services_offered": "Doorstep bike service, breakdown, periodic service",
        "rating": "Website — 500+ bikes serviced",
        "hours": "7 days 9 AM - 9 PM",
        "service_areas": "Wakad, Hinjewadi, Pimpri, Chinchwad, Ravet, 50+ areas",
        "source": "bikefixpune.in",
        "notes": "No fixed shop — service-area business",
        "service_ids": ["tw-mechanic", "tw-fix", "tw-pickup", "tw-wash"],
    },
    {
        "business_name": "KP Biker Zone",
        "contact_person": "",
        "shop_office": "Jagtap Complex",
        "building": "SNO- 79/1/1, Jagtap Complex",
        "street": "Sudarshan Nagar",
        "area": "Pimple Gurav",
        "city": "Pimpri-Chinchwad",
        "pin": "411061",
        "state": "Maharashtra",
        "phone1": "+91 8263805949",
        "phone2": "",
        "email1": "contact@kpbikerzone.com",
        "email2": "",
        "website": "https://kpbikerzone.in/bikes/pune/pimpri-chinchwad/",
        "maps_name": "KP Biker Zone Pimpri Chinchwad",
        "services_offered": "Doorstep bike service, repair, wash, pick-up drop to workshop",
        "rating": "Website",
        "hours": "",
        "service_areas": "Pimpri, Chinchwad, Wakad, Hinjewadi, Rahatani",
        "source": "kpbikerzone.in",
        "notes": "",
        "service_ids": ["tw-mechanic", "tw-fix", "tw-wash", "tw-deep", "tw-pickup"],
    },
    # ── Four-wheeler ──
    {
        "business_name": "GaadiMech Pune",
        "contact_person": "",
        "shop_office": "GaadiMech (doorstep car service)",
        "building": "",
        "street": "",
        "area": "Pune & PCMC",
        "city": "Pune",
        "pin": "",
        "state": "Maharashtra",
        "phone1": "+91 8448285289",
        "phone2": "",
        "email1": "",
        "email2": "",
        "website": "https://www.gaadimech.com/car-service-in-pune",
        "maps_name": "GaadiMech car service Pune",
        "services_offered": "Doorstep periodic service, pick-up drop, 90-min express",
        "rating": "Website",
        "hours": "8 AM - 8 PM, 7 days",
        "service_areas": "Hinjewadi, Wakad, Pimpri, Baner, Kothrud, Viman Nagar",
        "source": "gaadimech.com",
        "notes": "From ₹1,999 doorstep service",
        "service_ids": ["fw-mechanic", "fw-maintenance", "fw-pickup", "fw-fix"],
    },
    {
        "business_name": "Wisedrive Pune",
        "contact_person": "",
        "shop_office": "Wisedrive (doorstep)",
        "building": "",
        "street": "",
        "area": "Pune",
        "city": "Pune",
        "pin": "",
        "state": "Maharashtra",
        "phone1": "+91 9905129146",
        "phone2": "",
        "email1": "",
        "email2": "",
        "website": "https://www.wisedrive.com/car-service/pune",
        "maps_name": "Wisedrive doorstep car service Pune",
        "services_offered": "Doorstep car service, AC, battery, brakes, detailing",
        "rating": "Website — 200k+ jobs",
        "hours": "Same-day 30-min slots",
        "service_areas": "Pune city & suburbs",
        "source": "wisedrive.com",
        "notes": "WhatsApp booking",
        "service_ids": ["fw-mechanic", "fw-maintenance", "fw-fix", "fw-wash", "fw-detail"],
    },
    {
        "business_name": "Fix N Ride Pune",
        "contact_person": "",
        "shop_office": "Fix N Ride",
        "building": "",
        "street": "",
        "area": "Pune",
        "city": "Pune",
        "pin": "",
        "state": "Maharashtra",
        "phone1": "+91 7249199430",
        "phone2": "",
        "email1": "",
        "email2": "",
        "website": "https://fixnride.in/",
        "maps_name": "Fix N Ride car bike repair Pune",
        "services_offered": "Doorstep car & bike repair, pick-up, battery, tyre",
        "rating": "Website",
        "hours": "",
        "service_areas": "Pune, PCMC",
        "source": "fixnride.in",
        "notes": "Visiting charge ₹349",
        "service_ids": ["fw-fix", "fw-mechanic", "tw-mechanic", "tw-fix"],
    },
    {
        "business_name": "Unity Car Works",
        "contact_person": "",
        "shop_office": "Unity Car Works",
        "building": "Near Kate Petrol Pump, Mithila Nagari",
        "street": "Besides Gareeb Nawaj Biryani",
        "area": "Pimple Saudagar",
        "city": "Pimpri Chinchwad",
        "pin": "411027",
        "state": "Maharashtra",
        "phone1": "+91 9143844844",
        "phone2": "",
        "email1": "unitycaroworks@gmail.com",
        "email2": "",
        "website": "https://unitycarworks.com/",
        "maps_name": "Unity Car Works Pimple Saudagar",
        "services_offered": "Car repair, maintenance, detailing, emergency assist",
        "rating": "Website",
        "hours": "Mon-Sat 8am-6pm, Sun 8am-3pm",
        "service_areas": "Pimple Saudagar, PCMC, Pune",
        "source": "unitycarworks.com",
        "notes": "",
        "service_ids": ["fw-mechanic", "fw-maintenance", "fw-fix", "fw-wash", "fw-deep"],
    },
    # ── Food ──
    {
        "business_name": "PHD Meals",
        "contact_person": "",
        "shop_office": "PHD Meals Kitchen",
        "building": "C/o Happy Co Live PG 130/11",
        "street": "Shankar Kalat Nagar",
        "area": "Wakad",
        "city": "Pune",
        "pin": "411057",
        "state": "Maharashtra",
        "phone1": "+91 8459893110",
        "phone2": "",
        "email1": "support@phdmeals.in",
        "email2": "",
        "website": "https://phdmeals.in/",
        "maps_name": "PHD Meals Wakad tiffin",
        "services_offered": "Home-style tiffin, corporate lunch, weekly/monthly plans",
        "rating": "Website",
        "hours": "Mon-Sat 10:30 AM - 9:30 PM",
        "service_areas": "Wakad, Baner, Balewadi, Hinjewadi, Tathawade",
        "source": "phdmeals.in",
        "notes": "",
        "service_ids": ["fd-tiffin", "fd-office", "fd-breakfast"],
    },
    {
        "business_name": "Tiffin Daily",
        "contact_person": "",
        "shop_office": "Tiffin Daily",
        "building": "",
        "street": "",
        "area": "Wakad / PCMC",
        "city": "Pune",
        "pin": "",
        "state": "Maharashtra",
        "phone1": "+91 9975436663",
        "phone2": "",
        "email1": "info@tiffindaily.in",
        "email2": "",
        "website": "https://tiffindaily.in/",
        "maps_name": "Tiffin Daily Pune",
        "services_offered": "Monthly tiffin plans, veg/non-veg, trial meals",
        "rating": "Website",
        "hours": "Order lunch by 7 AM, dinner by 4 PM",
        "service_areas": "Wakad, Hinjewadi, Punawale, Baner, Aundh, PCMC",
        "source": "tiffindaily.in",
        "notes": "",
        "service_ids": ["fd-tiffin", "fd-breakfast", "fd-office"],
    },
    {
        "business_name": "Mauli Tiffin Service",
        "contact_person": "",
        "shop_office": "Mauli Tiffin Service",
        "building": "41/1",
        "street": "Parkhe Vasti",
        "area": "Wakad",
        "city": "Pune",
        "pin": "411057",
        "state": "Maharashtra",
        "phone1": "+91 7219734697",
        "phone2": "",
        "email1": "",
        "email2": "",
        "website": "https://www.zomato.com/pune/mauli-tiffin-service-wakad",
        "maps_name": "Mauli Tiffin Service Wakad",
        "services_offered": "North Indian tiffin — breakfast, lunch, dinner delivery",
        "rating": "Zomato listing",
        "hours": "Delivery only",
        "service_areas": "Wakad, PCMC",
        "source": "Zomato",
        "notes": "",
        "service_ids": ["fd-tiffin", "fd-restaurant"],
    },
    # ── Health ──
    {
        "business_name": "Sparkle Nursing Bureau",
        "contact_person": "",
        "shop_office": "Sparkle Nursing Bureau",
        "building": "Office near Bhumkar Chowk",
        "street": "",
        "area": "Wakad",
        "city": "Pune",
        "pin": "411057",
        "state": "Maharashtra",
        "phone1": "+91 7722000812",
        "phone2": "+91 8108595001",
        "email1": "info@sparklebureau.in",
        "email2": "",
        "website": "https://sparklebureau.in/",
        "maps_name": "Sparkle Nursing Bureau Wakad",
        "services_offered": "Home nursing, elderly care, ICU nurses, 24/7 attendants",
        "rating": "Website",
        "hours": "24/7",
        "service_areas": "Wakad, Hinjewadi, Baner, Pimple Saudagar, PCMC",
        "source": "sparklebureau.in",
        "notes": "",
        "service_ids": ["hl-elder", "hl-nursing", "hl-doctor"],
    },
    {
        "business_name": "MA Health Care Foundation",
        "contact_person": "Mrs. Madhuri Gurav",
        "shop_office": "MA Health Care Foundation",
        "building": "Jankar Residency, Shiv Shambho Colony",
        "street": "Adarsh Nagar Rd, Kiwale",
        "area": "Ravet",
        "city": "Pimpri-Chinchwad",
        "pin": "412101",
        "state": "Maharashtra",
        "phone1": "+91 9156567152",
        "phone2": "",
        "email1": "",
        "email2": "",
        "website": "https://mahealthfoundation.in/",
        "maps_name": "MA Health Care nursing bureau Ravet",
        "services_offered": "Home nursing, patient care, babysitting, medical equipment rental",
        "rating": "Website — 15+ years",
        "hours": "24/7",
        "service_areas": "Wakad, Ravet, PCMC, Thergaon, Pimple Saudagar",
        "source": "mahealthfoundation.in",
        "notes": "",
        "service_ids": ["hl-elder", "hl-nursing", "hl-specialist"],
    },
    {
        "business_name": "Omika Health Care",
        "contact_person": "",
        "shop_office": "Omika Health Care",
        "building": "",
        "street": "",
        "area": "Pune",
        "city": "Pune",
        "pin": "",
        "state": "Maharashtra",
        "phone1": "+91 9833988899",
        "phone2": "+91 9990211277",
        "email1": "",
        "email2": "",
        "website": "https://omikahealthcare.com/nursing-service-in-pune/",
        "maps_name": "Omika Health Care Pune nursing",
        "services_offered": "12/24 hr nursing at home, IV, injections, post-op care",
        "rating": "Website",
        "hours": "24/7",
        "service_areas": "Pune, PCMC",
        "source": "omikahealthcare.com",
        "notes": "",
        "service_ids": ["hl-nursing", "hl-elder", "hl-doctor"],
    },
    # ── Legal ──
    {
        "business_name": "Advocate Haji Karamatulla Khan Kadri",
        "contact_person": "Haji Karamatulla Khan Kadri",
        "shop_office": "Advocate office",
        "building": "Plot No 8, Sec 30/32",
        "street": "Chintamani Mandir Road, Walhekarwadi",
        "area": "Chinchwad",
        "city": "Pimpri Chinchwad",
        "pin": "411033",
        "state": "Maharashtra",
        "phone1": "+91 7276869192",
        "phone2": "+91 9834988568",
        "email1": "advkhan785@gmail.com",
        "email2": "",
        "website": "https://www.advhajikaramat.in/",
        "maps_name": "Advocate Haji Karamatulla Khan Kadri Chinchwad",
        "services_offered": "Family, criminal, civil, property, tax, divorce, registration",
        "rating": "Website",
        "hours": "",
        "service_areas": "Pimpri Chinchwad, Pune, Maharashtra",
        "source": "advhajikaramat.in",
        "notes": "",
        "service_ids": ["lg-consult", "lg-court", "lg-family", "lg-property-reg", "lg-contract"],
    },
    {
        "business_name": "Samyak Nahata Law Firm",
        "contact_person": "Adv. Samyak Nahata",
        "shop_office": "The Jewel Of Pimpri",
        "building": "Office No.25, B Wing",
        "street": "Kamala Cross Rd, near PCMC Building, MIDC",
        "area": "Pimpri Colony",
        "city": "Pimpri-Chinchwad",
        "pin": "411018",
        "state": "Maharashtra",
        "phone1": "+91 8999355609",
        "phone2": "",
        "email1": "samyak2399@gmail.com",
        "email2": "",
        "website": "https://advsamyakdhirajnahata.in/",
        "maps_name": "Samyak Nahata Law Firm Pimpri",
        "services_offered": "Divorce, criminal, consumer, cyber, civil, family law",
        "rating": "Website",
        "hours": "",
        "service_areas": "Pune, Pimpri-Chinchwad",
        "source": "advsamyakdhirajnahata.in",
        "notes": "",
        "service_ids": ["lg-consult", "lg-family", "lg-contract", "lg-doc-draft"],
    },
    # ── Property ──
    {
        "business_name": "Estate Rabbit Wakad",
        "contact_person": "",
        "shop_office": "Estate Rabbit",
        "building": "",
        "street": "",
        "area": "Wakad",
        "city": "Pune",
        "pin": "411057",
        "state": "Maharashtra",
        "phone1": "+91 8483850070",
        "phone2": "",
        "email1": "Info@estaterabbit.com",
        "email2": "",
        "website": "https://estaterabbit.com/flats-on-rent-in-wakad/",
        "maps_name": "Estate Rabbit flats on rent Wakad",
        "services_offered": "Flats on rent, buy/sell assistance, site visits, Wakad & West Pune",
        "rating": "Website",
        "hours": "",
        "service_areas": "Wakad, Hinjewadi, Baner, Balewadi, PCMC",
        "source": "estaterabbit.com",
        "notes": "",
        "service_ids": ["pr-rent", "pr-buy", "pr-site"],
    },
    {
        "business_name": "Pune Rentals",
        "contact_person": "",
        "shop_office": "Pune Rentals",
        "building": "",
        "street": "Shankar Kalat Nagar",
        "area": "Wakad",
        "city": "Pimpri Chinchwad",
        "pin": "411057",
        "state": "Maharashtra",
        "phone1": "+91 9540907979",
        "phone2": "",
        "email1": "",
        "email2": "",
        "website": "https://pune-rentals.com/",
        "maps_name": "Pune Rentals Wakad",
        "services_offered": "Rent flats, PG, site visits, tenant matching",
        "rating": "Website",
        "hours": "",
        "service_areas": "Wakad, PCMC, Pune",
        "source": "pune-rentals.com",
        "notes": "",
        "service_ids": ["pr-rent", "pr-site", "pr-commercial"],
    },
    {
        "business_name": "Corporate Leasing Pune",
        "contact_person": "",
        "shop_office": "Corporate Leasing Pune",
        "building": "",
        "street": "Orbit Heritage, Wakad",
        "area": "Wakad",
        "city": "Pune",
        "pin": "411057",
        "state": "Maharashtra",
        "phone1": "+91 8788800500",
        "phone2": "",
        "email1": "",
        "email2": "",
        "website": "https://corporateleasingpune.com/",
        "maps_name": "Corporate Leasing Pune Wakad",
        "services_offered": "Corporate rentals, furnished flats, commercial leasing",
        "rating": "Website",
        "hours": "",
        "service_areas": "Wakad, Pune, PCMC",
        "source": "corporateleasingpune.com",
        "notes": "",
        "service_ids": ["pr-rent", "pr-commercial", "pr-buy"],
    },
    # ── Cloud / IT ──
    {
        "business_name": "Core IT Solution (CITS)",
        "contact_person": "",
        "shop_office": "Shital Plaza Shop No. 10",
        "building": "Shital Plaza",
        "street": "Hinjawadi Road, Opposite Hinjewadi Grampanchayat Building",
        "area": "Hinjewadi",
        "city": "Pune",
        "pin": "411057",
        "state": "Maharashtra",
        "phone1": "+91 9762554009",
        "phone2": "+91 9372554009",
        "email1": "servicescoreit@gmail.com",
        "email2": "",
        "website": "https://coreit.in/",
        "maps_name": "Core IT Solution Hinjewadi",
        "services_offered": "Laptop/PC repair, hardware supply, IT support Hinjewadi",
        "rating": "Google reviews on website",
        "hours": "Mon-Sun 10 AM - 8 PM",
        "service_areas": "Hinjewadi, Wakad, Pune",
        "source": "coreit.in + Sulekha",
        "notes": "",
        "service_ids": ["cl-hardware", "cl-managed", "cl-network"],
    },
    {
        "business_name": "Infodot Technologies",
        "contact_person": "",
        "shop_office": "Infodot Technologies",
        "building": "",
        "street": "",
        "area": "Hinjewadi / Pune",
        "city": "Pune",
        "pin": "",
        "state": "Maharashtra",
        "phone1": "+91 9343735067",
        "phone2": "",
        "email1": "sales@infodot.co.in",
        "email2": "",
        "website": "https://infodot.co.in/it-services/managed-it-services-in-pune/",
        "maps_name": "Infodot managed IT services Pune",
        "services_offered": "Managed IT, cybersecurity, 24/7 monitoring, backup & DR",
        "rating": "Website",
        "hours": "",
        "service_areas": "Hinjewadi, Kharadi, Magarpatta, PCMC, Wakad",
        "source": "infodot.co.in",
        "notes": "On-site across Pune MMR",
        "service_ids": ["cl-managed", "cl-backup", "cl-infra-audit", "cl-maas"],
    },
    {
        "business_name": "Krezup IT Infrastructure",
        "contact_person": "",
        "shop_office": "Krezup",
        "building": "",
        "street": "",
        "area": "Pune & MIDC",
        "city": "Pune",
        "pin": "",
        "state": "Maharashtra",
        "phone1": "+91 9145361357",
        "phone2": "",
        "email1": "",
        "email2": "",
        "website": "https://krezup.in/",
        "maps_name": "Krezup IT infrastructure Pune",
        "services_offered": "Data center, networking, cabling, server install, AMC",
        "rating": "Website",
        "hours": "",
        "service_areas": "Hinjewadi, Wakad, PCMC, Chakan, Kharadi",
        "source": "krezup.in",
        "notes": "",
        "service_ids": ["cl-datacenter", "cl-network", "cl-hardware", "cl-dc-operate"],
    },
    # ── VIP ──
    {
        "business_name": "Pravasi Cab Wakad",
        "contact_person": "",
        "shop_office": "Pravasi Cab",
        "building": "",
        "street": "",
        "area": "Wakad",
        "city": "Pune",
        "pin": "411057",
        "state": "Maharashtra",
        "phone1": "+91 8149817272",
        "phone2": "",
        "email1": "",
        "email2": "",
        "website": "https://pravasicab.com/cab-service-wakad-pune",
        "maps_name": "Pravasi Cab Wakad airport taxi",
        "services_offered": "24/7 airport transfer, premium sedans/SUVs, corporate billing",
        "rating": "Website",
        "hours": "24/7",
        "service_areas": "Wakad, PCMC, Pune Airport, outstation",
        "source": "pravasicab.com",
        "notes": "VIP airport & chauffeur partner candidate",
        "service_ids": ["vip-airport", "vip-concierge"],
    },
    {
        "business_name": "K K Travels",
        "contact_person": "",
        "shop_office": "K K Travels",
        "building": "",
        "street": "",
        "area": "Pune",
        "city": "Pune",
        "pin": "",
        "state": "Maharashtra",
        "phone1": "+91 9822979797",
        "phone2": "",
        "email1": "",
        "email2": "",
        "website": "https://www.kktravels.com/",
        "maps_name": "KK Travels Pune airport transfer",
        "services_offered": "Airport transfers, corporate travel, holiday tours, 150+ owned cabs",
        "rating": "Website — est. 1995",
        "hours": "24/7",
        "service_areas": "Pune, Mumbai, Nashik airports",
        "source": "kktravels.com",
        "notes": "",
        "service_ids": ["vip-airport", "vip-event", "vip-concierge"],
    },
    {
        "business_name": "Shreeram Cabs",
        "contact_person": "",
        "shop_office": "Office No. 1, P.S.Terrace",
        "building": "P.S.Terrace",
        "street": "Sasane Nagar",
        "area": "Hadapsar",
        "city": "Pune",
        "pin": "411028",
        "state": "Maharashtra",
        "phone1": "+91 9373520808",
        "phone2": "",
        "email1": "booking@shreeramcab.com",
        "email2": "",
        "website": "https://www.shreeramcab.com/",
        "maps_name": "Shreeram Cabs Pune airport",
        "services_offered": "Premium airport pickup/drop, sedans/Innova, corporate travellers",
        "rating": "Website",
        "hours": "24/7",
        "service_areas": "Wakad, Hinjewadi, Baner, PCMC, Pune Airport",
        "source": "shreeramcab.com",
        "notes": "",
        "service_ids": ["vip-airport", "vip-assistant"],
    },
]
