-- Sync canonical metadata for all 98 catalog rows (10 home cards + 88 sub-services).
-- Trigger sync_public_prices updates service_prices_public automatically.

UPDATE service_pricing sp
SET
  parent_id = m.parent_id,
  is_category = m.is_category,
  card = m.card,
  sub_card = m.sub_card,
  service_name = m.service_name,
  sub_service_name = m.sub_service_name,
  theme = m.theme,
  unit = m.unit,
  icon = m.icon,
  updated_at = NOW()
FROM (VALUES
  ('legal', NULL, true, 'Legal & Consulting', '—', 'Legal & Consulting', 'Lawyers · docs · registration · 25% off', 'default', 'visit', '⚖️'),
  ('cloud', NULL, true, 'AI, Cloud & Data Center', '—', 'AI, Cloud & Data Center', 'AI · cloud · data center · 18 services', 'default', 'visit', '☁️'),
  ('vip', NULL, true, 'VIP Concierge', '—', 'VIP Concierge', 'Concierge · travel · events · 25% off', 'default', 'visit', '👑'),
  ('health', NULL, true, 'Health at Home', '—', 'Health at Home', 'Doctors · tests · pharmacy · 25% off', 'default', 'visit', '🏥'),
  ('property', NULL, true, 'Property & Rentals', '—', 'Property & Rentals', 'Buy · rent · verify · 25% off', 'default', 'visit', '🏡'),
  ('household', NULL, true, 'Cleaning & Home Help', '—', 'Cleaning & Home Help', 'Deep clean · home help · 25% off', 'default', 'visit', '🧹'),
  ('delivery', NULL, true, 'Courier & Deliveries', '—', 'Courier & Deliveries', 'Courier · parcels · express · 25% off', 'default', 'visit', '📦'),
  ('food', NULL, true, 'Food & Restaurants & Bars', '—', 'Food & Restaurants & Bars', 'Tiffin · restaurants · bars · 25% off', 'default', 'visit', '🍱'),
  ('two-wheeler', NULL, true, 'Bike Care', '—', 'Bike Care', 'Mechanic · pick-up · wash · 8 services', 'default', 'visit', '🛵'),
  ('four-wheeler', NULL, true, 'Car Care', '—', 'Car Care', 'Car service · pick-up · sanitization · 8 services', 'default', 'visit', '🚗'),
  ('hh-bathroom-deep', 'household', false, 'Cleaning & Home Help', 'Deep cleaning', 'Bathroom Deep Clean', 'Deep scrub · sanitise · 45–60 min', 'pink', 'visit', '🚿'),
  ('hh-kitchen-deep', 'household', false, 'Cleaning & Home Help', 'Deep cleaning', 'Kitchen Deep Clean', 'Counters · chimney · floor · grease', 'pink', 'visit', '🍳'),
  ('hh-flat-clean', 'household', false, 'Cleaning & Home Help', 'Deep cleaning', 'Full Flat Cleaning', 'Complete home · 1–3 BHK · 3–5 hrs', 'pink', 'visit', '🏠'),
  ('hh-care-plan', 'household', false, 'Cleaning & Home Help', 'Deep cleaning', 'Bathroom Care Plan', 'Weekly / fortnightly · fixed slot', 'pink', 'month', '📅'),
  ('hh-quick-clean', 'household', false, 'Cleaning & Home Help', 'Deep cleaning', 'Quick Clean', 'Single task · bathroom · fan · 30 min', 'pink', 'visit', '✨'),
  ('hh-sofa-clean', 'household', false, 'Cleaning & Home Help', 'Deep cleaning', 'Sofa & Upholstery Clean', 'Fabric · cushions · stain treatment · 1–2 hrs', 'pink', 'visit', '🛋️'),
  ('hh-house-help', 'household', false, 'Cleaning & Home Help', 'Home help', 'House Help', 'Sweep · mop · dust · multi-task · hourly', 'green', 'hour', '🏡'),
  ('hh-dishwashing', 'household', false, 'Cleaning & Home Help', 'Home help', 'Dishwashing', 'Utensils · sink · platform wipe', 'green', 'hour', '🍽️'),
  ('hh-kitchen-help', 'household', false, 'Cleaning & Home Help', 'Home help', 'Kitchen Tidy-Up', 'Platform · tiles · chimney wipe', 'green', 'hour', '🧽'),
  ('hh-fan-clean', 'household', false, 'Cleaning & Home Help', 'Home help', 'Fan Cleaning', 'Ceiling fan · blades · reachable only', 'green', 'visit', '🌀'),
  ('hh-window-clean', 'household', false, 'Cleaning & Home Help', 'Home help', 'Window Cleaning', 'Glass · frames · inside only', 'green', 'visit', '🪟'),
  ('hh-laundry', 'household', false, 'Cleaning & Home Help', 'Home help', 'Laundry Help', 'Fold · sort · organise wardrobe', 'green', 'hour', '👕'),
  ('hh-bathroom-help', 'household', false, 'Cleaning & Home Help', 'Home help', 'Bathroom Refresh', 'WC · floor · taps · hourly', 'green', 'hour', '🛁'),
  ('hh-ironing', 'household', false, 'Cleaning & Home Help', 'Home help', 'Ironing & Pressing', 'Shirts · sarees · formals · hourly', 'green', 'hour', '👔'),
  ('cl-iaas', 'cloud', false, 'AI, Cloud & Data Center', 'Cloud hosting', 'Cloud Compute (IaaS)', 'Virtual servers · storage · scale on demand', 'host', 'month', '🖥️'),
  ('cl-paas', 'cloud', false, 'AI, Cloud & Data Center', 'Cloud hosting', 'App Platform (PaaS)', 'Deploy apps · skip server management', 'host', 'month', '⚙️'),
  ('cl-saas', 'cloud', false, 'AI, Cloud & Data Center', 'Cloud hosting', 'Business Apps (SaaS)', 'Ready software · subscribe & go', 'host', 'month', '📱'),
  ('cl-hybrid', 'cloud', false, 'AI, Cloud & Data Center', 'Cloud hosting', 'Hybrid Cloud Setup', 'On-prem + cloud · unified control', 'host', 'project', '🔀'),
  ('cl-datacenter', 'cloud', false, 'AI, Cloud & Data Center', 'Infrastructure', 'Data Center Consulting', 'Design · build · optimise facilities', 'build', 'project', '🏢'),
  ('cl-network', 'cloud', false, 'AI, Cloud & Data Center', 'Infrastructure', 'Enterprise Networking', 'LAN · WAN · secure connectivity', 'build', 'project', '🌐'),
  ('cl-hardware', 'cloud', false, 'AI, Cloud & Data Center', 'Infrastructure', 'IT Hardware Supply', 'Servers · storage · laptops · networking', 'build', 'project', '💻'),
  ('cl-infra-audit', 'cloud', false, 'AI, Cloud & Data Center', 'Infrastructure', 'Infrastructure Audit & Roadmap', 'Assess · benchmark · 12-month upgrade plan', 'build', 'project', '📋'),
  ('cl-managed', 'cloud', false, 'AI, Cloud & Data Center', 'Managed & media', 'Managed IT Services', '24×7 monitoring · IAM · proactive ops', 'care', 'month', '🛡️'),
  ('cl-backup', 'cloud', false, 'AI, Cloud & Data Center', 'Managed & media', 'Backup & Disaster Recovery', 'Snapshots · replication · restore drills', 'care', 'month', '💾'),
  ('cl-video', 'cloud', false, 'AI, Cloud & Data Center', 'Managed & media', 'Video & Streaming Platform', 'Secure delivery · education · media', 'care', 'month', '🎬'),
  ('cl-training', 'cloud', false, 'AI, Cloud & Data Center', 'Managed & media', 'Cloud & IT Training', 'Hands-on labs · certs · career tracks', 'care', 'course', '🎓'),
  ('cl-office-box', 'cloud', false, 'AI, Cloud & Data Center', 'Turnkey packages', 'Office IT-in-a-Box', 'Desks · Wi‑Fi · PCs · phones · go-live ready', 'pack', 'project', '📦'),
  ('cl-dc-operate', 'cloud', false, 'AI, Cloud & Data Center', 'Turnkey packages', 'Data Center Build & Run', 'Design · rack · power · operate · handover', 'pack', 'project', '🏗️'),
  ('cl-dr-pack', 'cloud', false, 'AI, Cloud & Data Center', 'Turnkey packages', 'Business Continuity Pack', 'Backup · failover · tested recovery playbooks', 'pack', 'project', '🔒'),
  ('cl-maas', 'cloud', false, 'AI, Cloud & Data Center', 'Turnkey packages', 'Monitoring-as-a-Service', 'Dashboards · alerts · compliance views', 'pack', 'month', '📊'),
  ('cl-edtech', 'cloud', false, 'AI, Cloud & Data Center', 'Turnkey packages', 'Learning Platform Pack', 'LMS · secure video · student portal', 'pack', 'project', '📚'),
  ('cl-ott-pack', 'cloud', false, 'AI, Cloud & Data Center', 'Turnkey packages', 'Streaming Platform Pack', 'Catalogue · player · CDN · monetisation ready', 'pack', 'project', '📺'),
  ('lg-consult', 'legal', false, 'Legal & Consulting', 'Consultation & court', 'Lawyer Consultation', '30-min advice · civil · property · family', 'counsel', 'visit', '⚖️'),
  ('lg-court', 'legal', false, 'Legal & Consulting', 'Consultation & court', 'Court Filing & Notices', 'Draft · file · track · represent', 'counsel', 'project', '🏛️'),
  ('lg-contract', 'legal', false, 'Legal & Consulting', 'Consultation & court', 'Business Contract Review', 'Vendor · lease · employment · NDAs', 'counsel', 'project', '📋'),
  ('lg-family', 'legal', false, 'Legal & Consulting', 'Consultation & court', 'Family & Divorce Consult', 'Marriage · custody · maintenance · mediation', 'counsel', 'visit', '👨‍👩‍👧'),
  ('lg-doc-draft', 'legal', false, 'Legal & Consulting', 'Documents & registration', 'Document Drafting', 'Agreements · wills · affidavits · deeds', 'docs', 'project', '📝'),
  ('lg-property-reg', 'legal', false, 'Legal & Consulting', 'Documents & registration', 'Property Registration', 'Sale deed · gift · lease · index II', 'docs', 'project', '🏠'),
  ('lg-notary', 'legal', false, 'Legal & Consulting', 'Documents & registration', 'Notary & Affidavit', 'Attestation · sworn statements · copies', 'docs', 'visit', '✍️'),
  ('lg-rental', 'legal', false, 'Legal & Consulting', 'Documents & registration', 'Rental Agreement Pack', 'Draft · stamp · registration guidance · 11-month', 'docs', 'project', '🔑'),
  ('vip-concierge', 'vip', false, 'VIP Concierge', 'Concierge & assistant', '24×7 Personal Concierge', 'Tasks · bookings · reminders · errands', 'concierge', 'month', '👑'),
  ('vip-assistant', 'vip', false, 'VIP Concierge', 'Concierge & assistant', 'Executive Assistant', 'Calendar · calls · research · hourly', 'concierge', 'hour', '💼'),
  ('vip-priority', 'vip', false, 'VIP Concierge', 'Concierge & assistant', 'Priority Appointments', 'Doctors · lawyers · govt · fast-track', 'concierge', 'visit', '⭐'),
  ('vip-dining', 'vip', false, 'VIP Concierge', 'Concierge & assistant', 'Premium Dining Reservations', 'Top restaurants · private tables · occasions', 'concierge', 'visit', '🍷'),
  ('vip-airport', 'vip', false, 'VIP Concierge', 'Travel & events', 'Airport Transfer', 'Pickup · drop · meet & greet · Pune', 'travel', 'visit', '✈️'),
  ('vip-event', 'vip', false, 'VIP Concierge', 'Travel & events', 'Event Planning', 'Corporate · wedding · private · end-to-end', 'travel', 'project', '🎉'),
  ('hl-doctor', 'health', false, 'Health at Home', 'Home care', 'Doctor at Home', 'GP visit · vitals · prescription · PCMC', 'home', 'visit', '🩺'),
  ('hl-specialist', 'health', false, 'Health at Home', 'Home care', 'Specialist Consultation', 'Cardio · ortho · derma · paediatric', 'home', 'visit', '👨‍⚕️'),
  ('hl-elder', 'health', false, 'Health at Home', 'Home care', 'Elder Care Visit', 'Vitals · medication · mobility · hourly', 'home', 'hour', '🤝'),
  ('hl-nursing', 'health', false, 'Health at Home', 'Home care', 'Nursing Care at Home', 'Post-op · injections · wound dressings', 'home', 'hour', '💉'),
  ('hl-checkup', 'health', false, 'Health at Home', 'Tests & pharmacy', 'Full Body Checkup', '40+ tests · home sample · report', 'clinical', 'visit', '📋'),
  ('hl-lab', 'health', false, 'Health at Home', 'Tests & pharmacy', 'Lab Tests at Home', 'Blood · urine · single or panel', 'clinical', 'visit', '🧪'),
  ('hl-pharmacy', 'health', false, 'Health at Home', 'Tests & pharmacy', 'Pharmacy Delivery', 'Prescription · OTC · 60 min target', 'clinical', 'visit', '💊'),
  ('hl-vaccine', 'health', false, 'Health at Home', 'Tests & pharmacy', 'Vaccination at Home', 'Flu · hepatitis · travel · corporate camps', 'clinical', 'visit', '💉'),
  ('pr-buy', 'property', false, 'Property & Rentals', 'Find property', 'Buy / Sell Assistance', 'Shortlist · negotiate · close · PCMC', 'find', 'project', '🏘️'),
  ('pr-rent', 'property', false, 'Property & Rentals', 'Find property', 'Rent & PG Finder', 'Flat · PG · coliving · tenant match', 'find', 'project', '🔑'),
  ('pr-site', 'property', false, 'Property & Rentals', 'Find property', 'Site Visit Package', '3–5 properties · agent · same day', 'find', 'visit', '📍'),
  ('pr-commercial', 'property', false, 'Property & Rentals', 'Find property', 'Commercial Space Finder', 'Office · shop · warehouse · PCMC', 'find', 'project', '🏢'),
  ('pr-legal', 'property', false, 'Property & Rentals', 'Verify & finance', 'Legal Verification', 'Title · encumbrance · approvals · report', 'verify', 'project', '📑'),
  ('pr-loan', 'property', false, 'Property & Rentals', 'Verify & finance', 'Home Loan Assistance', 'Compare banks · paperwork · faster sanction', 'verify', 'project', '🏦'),
  ('dl-sameday', 'delivery', false, 'Courier & Deliveries', 'Local delivery', 'Same-Day Courier', 'Pickup in 60 min · PCMC · Pune', 'local', 'visit', '📦'),
  ('dl-doc', 'delivery', false, 'Courier & Deliveries', 'Local delivery', 'Document Delivery', 'Legal · bank · office · confidential', 'local', 'visit', '📄'),
  ('dl-parcel', 'delivery', false, 'Courier & Deliveries', 'Local delivery', 'Parcel Pickup & Drop', 'Gifts · ecommerce · returns · multi-stop', 'local', 'visit', '🎁'),
  ('dl-grocery', 'delivery', false, 'Courier & Deliveries', 'Local delivery', 'Grocery & Essentials Run', 'Kirana · milk · bread · 90 min target', 'local', 'visit', '🛒'),
  ('dl-intercity', 'delivery', false, 'Courier & Deliveries', 'Express & bulk', 'Inter-City Express', 'Maharashtra · overnight · tracked', 'express', 'project', '🚚'),
  ('dl-bulk', 'delivery', false, 'Courier & Deliveries', 'Express & bulk', 'Business Bulk Delivery', 'Daily routes · SLAs · invoicing', 'express', 'project', '🏢'),
  ('fd-tiffin', 'food', false, 'Food & Restaurants & Bars', 'Daily meals', 'Home Tiffin Plan', 'Veg · non-veg · monthly · 2 meals', 'daily', 'month', '🍱'),
  ('fd-restaurant', 'food', false, 'Food & Restaurants & Bars', 'Daily meals', 'Restaurant Order', 'Local restaurants · 30–60 min · track', 'daily', 'visit', '🍽️'),
  ('fd-office', 'food', false, 'Food & Restaurants & Bars', 'Daily meals', 'Office Lunch Box', 'Team orders · invoicing · daily menu', 'daily', 'month', '🥗'),
  ('fd-breakfast', 'food', false, 'Food & Restaurants & Bars', 'Daily meals', 'Breakfast & Snacks Plan', 'Morning tiffin · poha · idli · monthly', 'daily', 'month', '🥐'),
  ('fd-catering', 'food', false, 'Food & Restaurants & Bars', 'Catering & events', 'Party Catering', 'Birthday · corporate · 20–500 guests', 'events', 'project', '🎂'),
  ('fd-festival', 'food', false, 'Food & Restaurants & Bars', 'Catering & events', 'Festival Special Menu', 'Diwali · Ganesh · wedding sweets · bulk', 'events', 'project', '🪔'),
  ('tw-mechanic', 'two-wheeler', false, 'Bike Care', 'Roadside help', 'Mechanic Support', 'Breakdown · tune-up · at home or roadside', 'roadside', 'visit', '🔧'),
  ('tw-pickup', 'two-wheeler', false, 'Bike Care', 'Care & pickup', 'Pick-up & Drop Servicing', 'Garage run · service · return to doorstep', 'care', 'visit', '🛵'),
  ('tw-fix', 'two-wheeler', false, 'Bike Care', 'Roadside help', 'On-Road Fixing', 'Flat tyre · chain · fuse · minor electrical', 'roadside', 'visit', '⚡'),
  ('tw-wash', 'two-wheeler', false, 'Bike Care', 'Care & pickup', 'Bike Washing', 'Exterior wash · chain lube · 30 min', 'care', 'visit', '💦'),
  ('tw-deep', 'two-wheeler', false, 'Bike Care', 'Care & pickup', 'Deep Cleaning', 'Engine bay wipe · degrease · polish · 1–2 hrs', 'care', 'visit', '✨'),
  ('tw-polish', 'two-wheeler', false, 'Bike Care', 'Care & pickup', 'Bike Polish & Wax', 'Body wax · chrome shine · chain lube · 45 min', 'care', 'visit', '🪩'),
  ('tw-battery', 'two-wheeler', false, 'Bike Care', 'Roadside help', 'Battery & Tyre Check', 'Health test · air · replacement guidance', 'roadside', 'visit', '🔋'),
  ('tw-towing', 'two-wheeler', false, 'Bike Care', 'Roadside help', 'Emergency Towing', 'Breakdown tow · garage drop · 24×7 · PCMC', 'roadside', 'visit', '🚛'),
  ('fw-mechanic', 'four-wheeler', false, 'Car Care', 'Service & repair', 'Mechanic Support', 'Breakdown · diagnostics · home or roadside', 'service', 'visit', '🔧'),
  ('fw-pickup', 'four-wheeler', false, 'Car Care', 'Service & repair', 'Pick-up & Drop Servicing', 'Collect · service centre · return washed', 'service', 'visit', '🚗'),
  ('fw-fix', 'four-wheeler', false, 'Car Care', 'Service & repair', 'On-Site Fixing', 'Battery · tyre · minor electrical · fluid top-up', 'service', 'visit', '⚡'),
  ('fw-maintenance', 'four-wheeler', false, 'Car Care', 'Service & repair', 'Periodic Car Service', 'Oil change · filters · 10k km · partner garage', 'service', 'visit', '🔩'),
  ('fw-wash', 'four-wheeler', false, 'Car Care', 'Cleaning & care', 'Car Washing', 'Exterior wash · vacuum · 45–60 min', 'care', 'visit', '💦'),
  ('fw-deep', 'four-wheeler', false, 'Car Care', 'Cleaning & care', 'Deep Cleaning', 'Interior shampoo · AC vent · engine bay', 'care', 'visit', '✨'),
  ('fw-detail', 'four-wheeler', false, 'Car Care', 'Cleaning & care', 'Detailing & Interior', 'Polish · ceramic prep · leather care · premium', 'care', 'visit', '💎'),
  ('fw-sanitize', 'four-wheeler', false, 'Car Care', 'Cleaning & care', 'Interior Sanitization', 'Ozone · AC disinfect · fabric spray · 1 hr', 'care', 'visit', '🧴')
) AS m(service_id, parent_id, is_category, card, sub_card, service_name, sub_service_name, theme, unit, icon)
WHERE sp.service_id = m.service_id;
